# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_text', models.CharField(max_length=200)),
                ('code_text', models.CharField(max_length=10)),
                ('schoolname_text', models.CharField(max_length=200)),
                ('location_text', models.CharField(max_length=200)),
                ('contact_text', models.CharField(max_length=200)),
                ('tel_text', models.CharField(max_length=200)),
                ('email_text', models.CharField(max_length=200)),
                ('grade_text', models.CharField(max_length=200)),
                ('teachersnum_text', models.CharField(max_length=200)),
                ('studentnum_text', models.CharField(max_length=200)),
                ('fill_date', models.CharField(max_length=200)),
            ],
        ),
    ]
