# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_questionsort'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
