# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_userpoll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[(b'1', b'\xe5\x8d\x95\xe9\x80\x89\xe9\xa2\x98'), (b'2', b'\xe5\xa4\x9a\xe9\x80\x89\xe9\xa2\x98'), (b'3', b'\xe5\xa1\xab\xe7\xa9\xba\xe9\xa2\x98'), (b'4', b'\xe5\x88\xa4\xe6\x96\xad\xe9\xa2\x98')], default=b'1', max_length=200),
        ),
    ]
