# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_userpollanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpollanswer',
            name='answer_text',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
