# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160131_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpollanswer',
            name='questtion_id',
            field=models.IntegerField(default=1),
        ),
    ]
